//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CZSRMS_DBEntities : DbContext
    {
        public CZSRMS_DBEntities()
            : base("name=CZSRMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_FileInfo> tb_FileInfo { get; set; }
        public virtual DbSet<tb_LogInfo> tb_LogInfo { get; set; }
        public virtual DbSet<tb_UserInfo> tb_UserInfo { get; set; }
        public virtual DbSet<tb_CoodinateSystem> tb_CoodinateSystem { get; set; }
        public virtual DbSet<tb_FileType> tb_FileType { get; set; }
        public virtual DbSet<tb_ProjectType> tb_ProjectType { get; set; }
        public virtual DbSet<tb_Unit> tb_Unit { get; set; }
    }
}
