//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 批量上传文件
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FileInfo
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string Directory { get; set; }
        public string CoodinateSystem { get; set; }
        public string FinishtimeInfo { get; set; }
        public string FinishPersonInfo { get; set; }
        public Nullable<double> MinCoodinate { get; set; }
        public Nullable<double> MaxCoodinate { get; set; }
        public Nullable<int> ObjectNum { get; set; }
        public string Mark { get; set; }
        public Nullable<bool> Warehousing { get; set; }
        public string ProjectName { get; set; }
        public string FileType { get; set; }
        public string ProjectType { get; set; }
        public string PcoodinateSystem { get; set; }
        public string CenterMeridian { get; set; }
        public Nullable<double> Yoffset { get; set; }
        public Nullable<double> Xoffset { get; set; }
        public string Finishtime { get; set; }
        public string FinishPerson { get; set; }
        public string SurveyingUnitName { get; set; }
        public string Explain { get; set; }
        public string PublicObjs { get; set; }
        public string UploadTime { get; set; }
        public double FileSize { get; set; }
        public int UserID { get; set; }
        public string ObjectID { get; set; }
        public string MD5 { get; set; }
        public bool WasDeleted { get; set; }
    }
}
